## Setting up the database connection

In [1]:
#Imports

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import sqlite3
import matplotlib.pyplot as plt

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

#path = "../input/"  #Insert path here
database = 'database.sqlite'
conn = sqlite3.connect(database)

### Focus will be on the "Player_Attributes" table (and the "Player" Table)

In [7]:
pd.set_option('display.max_columns', None) #to display all columns
pd.read_sql("""SELECT * FROM Player_Attributes ORDER BY overall_rating desc LIMIT 10 ;""", conn)

,id,player_fifa_api_id,player_api_id,date,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,finishing,heading_accuracy,short_passing,volleys,dribbling,curve,free_kick_accuracy,long_passing,ball_control,acceleration,sprint_speed,agility,reactions,balance,shot_power,jumping,stamina,strength,long_shots,aggression,interceptions,positioning,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
0,102483,158023,30981,2015-12-17 00:00:00,94,94,left,medium,low,80,93,71,88,85,96,89,90,79,96,95,90,92,92,95,80,68,75,59,88,48,22,90,90,74,13,23,21,6,11,15,14,8
1,102484,158023,30981,2015-10-16 00:00:00,94,94,left,medium,low,80,93,71,88,85,96,89,90,79,96,95,90,92,92,95,80,68,75,59,88,48,22,90,90,74,13,23,21,6,11,15,14,8
2,102485,158023,30981,2015-09-21 00:00:00,94,95,left,medium,low,80,93,71,88,85,96,89,90,79,96,95,90,92,92,95,80,68,76,59,88,48,22,90,90,74,13,23,21,6,11,15,14,8
3,102492,158023,30981,2014-04-25 00:00:00,94,97,left,medium,low,84,97,71,89,90,97,87,86,76,96,96,88,94,96,95,81,73,78,60,88,48,22,93,90,76,25,21,20,6,11,15,14,8
4,102493,158023,30981,2013-11-15 00:00:00,94,97,left,high,medium,84,97,71,89,90,97,87,86,76,96,96,88,94,96,95,81,73,78,60,88,48,22,93,90,76,25,21,20,6,11,15,14,8
5,102494,158023,30981,2013-09-20 00:00:00,94,97,left,high,medium,84,97,71,89,90,97,87,86,76,96,96,88,94,96,95,81,73,78,60,88,48,22,93,90,76,25,21,20,6,11,15,14,8
6,102495,158023,30981,2013-03-22 00:00:00,94,97,left,high,medium,84,97,72,89,89,97,87,86,76,96,95,91,94,96,95,80,73,80,65,88,48,22,93,90,78,13,21,20,6,11,15,14,8
7,102496,158023,30981,2013-03-08 00:00:00,94,97,left,high,medium,84,97,72,89,89,97,87,86,76,96,95,91,94,96,95,80,73,80,65,88,48,22,93,90,78,13,21,20,6,11,15,14,8
8,102497,158023,30981,2013-02-15 00:00:00,94,97,left,high,medium,84,97,72,89,89,97,87,86,76,96,95,91,94,96,95,80,73,80,65,88,48,22,93,90,78,13,21,20,6,11,15,14,8
9,102498,158023,30981,2012-08-31 00:00:00,94,96,left,high,medium,85,95,73,89,89,97,87,82,75,96,95,92,94,95,95,80,73,80,67,88,48,22,92,90,76,13,21,20,6,11,15,14,8

#### Not surprisingly, Lionel Messi had the highest overall rating in this particular dataset
* Can also use the birthday column here to extract player's age

In [11]:
pd.read_sql("""SELECT * FROM player WHERE player_api_id = 30981;""", conn)

,id,player_api_id,player_name,player_fifa_api_id,birthday,height,weight
0,6176,30981,Lionel Messi,158023,1987-06-24 00:00:00,170.18,159

#### Besides the "overall_rating" and "potential", there's a lot of other data that can help assess a player's offensive or defensive capabilities.
* It may be interesting to see how these players received higher rating (if there's a fan-based element or if it's purely based on stats, e.g. a player received a higher rating if they had 'medium/high' attacking_work_rate and had good offensive abilities as well, and same way for the primarily defensive players.

### Data Types for the Player Attributes table
* Let's convert date (string) to datetime

In [12]:
pd.read_sql("""SELECT * FROM Player_Attributes ORDER BY overall_rating desc LIMIT 10 ;""", conn).dtypes

id                      int64
player_fifa_api_id      int64
player_api_id           int64
date                   object
overall_rating          int64
potential               int64
preferred_foot         object
attacking_work_rate    object
defensive_work_rate    object
crossing                int64
finishing               int64
heading_accuracy        int64
short_passing           int64
volleys                 int64
dribbling               int64
curve                   int64
free_kick_accuracy      int64
long_passing            int64
ball_control            int64
acceleration            int64
sprint_speed            int64
agility                 int64
reactions               int64
balance                 int64
shot_power              int64
jumping                 int64
stamina                 int64
strength                int64
long_shots              int64
aggression              int64
interceptions           int64
positioning             int64
vision                  int64
penalties               int64
marking                 int64
standing_tackle         int64
sliding_tackle          int64
gk_diving               int64
gk_handling             int64
gk_kicking              int64
gk_positioning          int64
gk_reflexes             int64
dtype: object

In [14]:
#183,978 rows for player attributes.
pd.read_sql("""SELECT count(*) FROM Player_Attributes ORDER BY overall_rating desc;""", conn)

   count(*)
0    183978

## Calculating Overall Summary Statistics
* This can help us get a better sense of the data, and maybe even get a sense of what's considered "average"